### ISSUE TITLE
mapa: cargar contenido popup en click

### ISSUE THREAD

**Issue by mgaitan** [concristina/carreros#5]
actualmente el mapa arma un popup para cada marcador de escuela y hace una peticion ajax para cargar el detalle. En vez de hacer todas las peticiones automaticamente deberia hacerse cuando se hace click (evento 'popupopen')

**Comment by mgaitan** [comment]
@pandres tuyo si queres

**Comment by mgaitan** [comment]
estimadisimos, alguien logró avanzar algo con esto?

**Comment by pandres** [comment]
Todavia estudiando eso. Consegui sacar el contenido de los popup para
generar el minimo codigo y despues llenar cada popup con ajax. Sinceramente
no se si leaflet  ofrece una forma piola de hacer eso, tengo que leer la
doc. Pushie una branch cq cosa.

**Comment by pandres** [comment]
https://github.com/concristina/carreros/pull/28

**Comment by mgaitan** [comment]
un espectaculo. gracias

**Comment by pandres** [comment]
Pasa otro
